---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth":
    post:
      summary: create authentication
      responses:
        '200':
          description: successful
  "/cars":
    get:
      summary: list cars
      responses:
        '200':
          description: successful
    post:
      summary: create car
      responses:
        '200':
          description: successful
  "/cars/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update car
      responses:
        '200':
          description: successful
    put:
      summary: update car
      responses:
        '200':
          description: successful
    delete:
      summary: delete car
      responses:
        '200':
          description: successful
  "/reservations":
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/register":
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/toggle_admin":
    post:
      summary: toggle_admin user
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
